# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TogeterJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_branch_id', models.IntegerField()),
                ('sender_room_id', models.IntegerField()),
                ('recv_branch_id', models.IntegerField()),
                ('recv_room_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TogeterJoinList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
                ('man_count', models.IntegerField(blank=True)),
                ('woman_count', models.IntegerField(blank=True)),
                ('our_ages', models.CharField(blank=True, max_length=5)),
                ('req_person_count', models.IntegerField(blank=True)),
                ('req_gender', models.IntegerField(blank=True)),
                ('req_age_begin', models.IntegerField(blank=True)),
                ('req_age_end', models.IntegerField(blank=True)),
                ('specials', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TogeterMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_branch_id', models.IntegerField()),
                ('sender_room_id', models.IntegerField()),
                ('recv_branch_id', models.IntegerField()),
                ('recv_room_id', models.IntegerField()),
                ('msg', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
