# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='togeterjoinlist',
            name='our_ages',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
