# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togeter', '0002_auto_20171203_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
                ('firebase_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
