# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togeter', '0003_firebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='togeterjoinlist',
            name='our_age_begin_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='togeterjoinlist',
            name='our_age_end_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
