# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togeter', '0004_auto_20171212_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='TogeterJoinAccept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_branch_id', models.IntegerField()),
                ('sender_room_id', models.IntegerField()),
                ('recv_branch_id', models.IntegerField()),
                ('recv_room_id', models.IntegerField()),
            ],
        ),
    ]
