# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togeter', '0005_togeterjoinaccept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebase',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
