# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togeter', '0006_auto_20171219_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebase',
            name='create_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='togeterjoin',
            name='create_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='togeterjoinaccept',
            name='create_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='togeterjoinlist',
            name='create_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='togetermessage',
            name='create_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
