# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togeter', '0007_auto_20171219_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='TogeterMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('sender_branch_id', models.IntegerField()),
                ('sender_room_id', models.IntegerField()),
                ('recv_branch_id', models.IntegerField()),
                ('recv_room_id', models.IntegerField()),
                ('msg', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
