# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0002_document_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='title',
        ),
    ]
