# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0003_auto_20171019_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='faq',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='created_date',
            field=models.CharField(max_length=50),
        ),
    ]
