# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0006_auto_20171023_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_uploaded_at',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='smi',
            old_name='smi_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='smi',
            old_name='smi_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='smi',
            old_name='smi_uploaded_at',
            new_name='uploaded_at',
        ),
    ]
