# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0007_auto_20171024_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='gameinfo_idx',
        ),
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=models.FileField(upload_to='movies/file/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='smi',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
