# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0008_auto_20171024_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='movies/file/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gameinfo_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.GameInfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
