# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0009_auto_20171025_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='gameinfo_idx',
        ),
        migrations.AddField(
            model_name='movies',
            name='gameinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo_id', to='gameinfo.GameInfo'),
            preserve_default=False,
        ),
    ]
