# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0010_auto_20171025_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='idx',
            field=models.IntegerField(null=True),
        ),
    ]
