# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0011_movies_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smi',
            old_name='file',
            new_name='file_smi',
        ),
        migrations.RemoveField(
            model_name='smi',
            name='gameinfo_idx',
        ),
        migrations.AddField(
            model_name='smi',
            name='gameinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo_smi', to='gameinfo.GameInfo'),
            preserve_default=False,
        ),
    ]
