# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0012_auto_20171025_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='idx',
        ),
        migrations.RemoveField(
            model_name='smi',
            name='cnt',
        ),
        migrations.RemoveField(
            model_name='smi',
            name='language',
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='desc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='media',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='setting',
            field=models.IntegerField(null=True),
        ),
    ]
