# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0013_auto_20171027_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smi',
            name='file_smi',
            field=models.FileField(upload_to='movies/smi/'),
        ),
    ]
