# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0014_auto_20171027_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smi',
            old_name='gameinfo',
            new_name='gameinfo_id',
        ),
    ]
