# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0015_auto_20171027_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='movies/subtitle/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gameinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo_subtitle', to='gameinfo.GameInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='smi',
            name='gameinfo_id',
        ),
        migrations.DeleteModel(
            name='Smi',
        ),
    ]
