# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0018_auto_20171030_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='language',
        ),
        migrations.AddField(
            model_name='movies',
            name='language_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '한국어'), (2, '영어'), (3, '중국어')], default=1),
            preserve_default=False,
        ),
    ]
