# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0019_auto_20171030_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cnt', models.CharField(blank=True, max_length=20)),
                ('language_type', models.PositiveSmallIntegerField(choices=[(1, '한국어'), (2, '영어'), (3, '중국어')])),
                ('gameinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo_detail', to='gameinfo.GameInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='cnt',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='language_type',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='subtitle_id',
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='movie_id',
            field=models.ManyToManyField(to='gameinfo.Movies'),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='subtitle_id',
            field=models.ManyToManyField(to='gameinfo.Subtitle'),
        ),
    ]
