# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0020_auto_20171101_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='language_type',
            field=models.CharField(choices=[('Kor', '한국어'), ('Eng', '영어'), ('Chn', '중국어')], max_length=5),
        ),
    ]
