# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0022_auto_20171108_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='idx',
        ),
    ]
