# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0023_remove_gameinfo_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='desc',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='faq',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='media',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='setting',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
