# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0024_auto_20171109_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinfo',
            old_name='faq',
            new_name='desc_cnt',
        ),
        migrations.RenameField(
            model_name='gameinfo',
            old_name='media',
            new_name='desc_time',
        ),
        migrations.RenameField(
            model_name='gameinfo',
            old_name='setting',
            new_name='faq_cnt',
        ),
        migrations.RemoveField(
            model_name='moviedetail',
            name='cnt',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='cnt',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='eng_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='genre_detail',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='level',
            field=models.CharField(choices=[('Very Hard', 'Very Hard'), ('Hard', 'Hard'), ('Normal', 'Normal'), ('Easy', 'Easy'), ('Very Easy', 'Very Easy')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='max_cnt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='media_cnt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='min_cnt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='play_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='setting_cnt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='tag',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='desc',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
