# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0025_auto_20171111_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='gameinfo/image/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='gameinfo/subimage/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='icon',
            field=models.CharField(choices=[('어린이추천', '어린이추천'), ('커플인기', '커플인기'), ('HOT', 'HOT'), ('매니아인기', '매니아인기'), ('남성인기', '남성인기'), ('초심자인기', '초심자인기'), ('직원추천', '직원추천'), ('수상작', '수상작'), ('여성인기', '여성인기')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='level',
            field=models.CharField(choices=[('Very Easy', 'Very Easy'), ('Easy', 'Easy'), ('Normal', 'Normal'), ('Hard', 'Hard'), ('Very Hard', 'Very Hard'), ('Extreme', 'Extreme'), ('ProGamer', 'ProGamer')], max_length=10),
        ),
        migrations.AddField(
            model_name='subimage',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo_subimage', to='gameinfo.GameInfo'),
        ),
        migrations.AddField(
            model_name='image',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo_image', to='gameinfo.GameInfo'),
        ),
    ]
