# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0027_auto_20171111_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameimage',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gameinfo.GameInfo'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_info', to='gameinfo.GameInfo'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='gameinfo.GameInfo'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle', to='gameinfo.GameInfo'),
        ),
    ]
