# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0028_auto_20171112_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameimage',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='gameinfo.GameInfo'),
        ),
    ]
