# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0029_auto_20171112_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
