# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0030_auto_20171122_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='icon',
            field=models.CharField(choices=[('어린이추천', '어린이추천'), ('커플인기', '커플인기'), ('HOT', 'HOT'), ('매니아인기', '매니아인기'), ('남성인기', '남성인기'), ('초심자인기', '초심자인기'), ('직원추천', '직원추천'), ('수상작', '수상작'), ('여성인기', '여성인기')], max_length=100),
        ),
    ]
