# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0031_auto_20171122_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='desc',
            field=models.TextField(max_length=200),
        ),
    ]
