# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0033_auto_20171126_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='level',
            field=models.CharField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Normal'), (4, 'Hard'), (5, 'Very Hard'), (6, 'Extreme'), (7, 'ProGamer')], max_length=10),
        ),
    ]
