# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0034_auto_20171126_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='level',
            field=models.CharField(choices=[('Very Easy', 'Very Easy'), ('Easy', 'Easy'), ('Normal', 'Normal'), ('Hard', 'Hard'), ('Very Hard', 'Very Hard'), ('Extreme', 'Extreme'), ('ProGamer', 'ProGamer')], max_length=10),
        ),
    ]
