# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0040_auto_20171127_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='icon',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
