# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0042_moviedetail_cnt_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='subtitle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
