# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0044_gameinfo_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='desc',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='faq',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='gameimage',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='movies',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subimage',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='summary',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
