# Generated by Django 2.0 on 2018-02-02 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0045_auto_20171227_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gameinfo_desc', to='gameinfo.GameInfo'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gameinfo_faq', to='gameinfo.GameInfo'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gameinfo_setting', to='gameinfo.GameInfo'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gameinfo_summary', to='gameinfo.GameInfo'),
        ),
    ]
