# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0046_auto_20180202_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.SmallIntegerField(default=0, null=True)),
                ('mix', models.IntegerField(default=0, null=True)),
                ('male', models.IntegerField(default=0, null=True)),
                ('female', models.IntegerField(default=0, null=True)),
                ('gameinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo_filters', to='gameinfo.GameInfo')),
            ],
        ),

        migrations.AlterField(
            model_name='desc',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo_desc', to='gameinfo.GameInfo'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo_faq', to='gameinfo.GameInfo'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo_setting', to='gameinfo.GameInfo'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='gameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo_summary', to='gameinfo.GameInfo'),
        ),
    ]
