# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20171121_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Super admin'), (2, 'General admin'), (3, 'Manager'), (4, 'Buttoner'), (5, 'Room')], null=True),
        ),
    ]
