# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20171122_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_user',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
