# Generated by Django 2.0 on 2018-04-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_profile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Super admin'), (2, 'General admin'), (3, 'Manager'), (4, 'Counter'), (5, 'Room')], null=True),
        ),
    ]
