# Generated by Django 2.2 on 2019-04-05 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('gameinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('user', models.CharField(blank=True, max_length=150)),
                ('is_view', models.BooleanField(default=0)),
                ('cant_explain', models.BooleanField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='branch.Branch')),
                ('gameinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo_branch', to='gameinfo.GameInfo')),
            ],
        ),
    ]
