# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.CharField(max_length=255, null=True)),
                ('movie_watch_cnt', models.IntegerField(blank=True, null=True)),
                ('volume_settting', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
