# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etc',
            name='movie_watch_cnt',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='etc',
            name='volume_settting',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
