# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0002_auto_20171130_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOpinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=150, null=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
