# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0005_auto_20171223_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='etc',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
