# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
