# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_auto_20171130_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_forbidden_word',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='is_note',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='is_together',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
