# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_auto_20171130_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
