# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_branch_is_guide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='is_guide',
            new_name='is_desc_request',
        ),
    ]
