# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_auto_20171227_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_guide',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
