# Generated by Django 2.0 on 2018-02-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0010_branch_forbidden_word_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='system_volume',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
